/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-05-04 04:36:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("    $(\"#homePage\").show();\n");
      out.write("    $(\"#createPage\").hide();\n");
      out.write("    $(\"#deletePage\").hide();\n");
      out.write("    $(\"#updatePage\").hide();\n");
      out.write("    \n");
      out.write("    $(\"#home\").click(function(){\n");
      out.write("        $(\"#homePage\").show();\n");
      out.write("        $(\"#createPage\").hide();\n");
      out.write("        $(\"#deletePage\").hide();\n");
      out.write("        $(\"#updatePage\").hide();\n");
      out.write("     });\n");
      out.write("    $(\"#create\").click(function(){\n");
      out.write("        $(\"#homePage\").hide();\n");
      out.write("        $(\"#createPage\").show();\n");
      out.write("        $(\"#deletePage\").hide();\n");
      out.write("        $(\"#updatePage\").hide();\n");
      out.write("     });\n");
      out.write("    $(\"#delete\").click(function(){\n");
      out.write("        $(\"#homePage\").hide();\n");
      out.write("        $(\"#createPage\").hide();\n");
      out.write("        $(\"#deletePage\").show();\n");
      out.write("        $(\"#updatePage\").hide();\n");
      out.write("        $('#delete_form').submit(function(){\n");
      out.write("        \tdeleteData($('.ids').val());\n");
      out.write("        \treturn false;\n");
      out.write("        });\n");
      out.write("        function deleteData(ids){\n");
      out.write("            $.ajax({\n");
      out.write("                    type: \"DELETE\",\n");
      out.write("                    url: ids,\n");
      out.write("                    success: function (data, status, jqXHR) {\n");
      out.write("                        alert(\"deleted\");\n");
      out.write("                    },\n");
      out.write("                    error: function (jqXHR, status) {\n");
      out.write("                        console.log(status);\n");
      out.write("                        alert('failed, please check console for errors');\n");
      out.write("                    }\n");
      out.write("                 });\n");
      out.write("           }\n");
      out.write("\n");
      out.write("     });\n");
      out.write("    $(\"#update\").click(function(){\n");
      out.write("        $(\"#homePage\").hide();\n");
      out.write("        $(\"#createPage\").hide();\n");
      out.write("        $(\"#deletePage\").hide();\n");
      out.write("        $(\"#updatePage\").show();\n");
      out.write("        $('#update_form').submit(function(){\n");
      out.write("        \tupdateData($('.id').val());\n");
      out.write("        \treturn false;\n");
      out.write("        });\n");
      out.write("        function updateData(id){\n");
      out.write("            $.ajax({\n");
      out.write("                    type: \"PUT\",\n");
      out.write("                    url: id,\n");
      out.write("                    success: function (data, status, jqXHR) {\n");
      out.write("                    \talert(data);\n");
      out.write("                    },\n");
      out.write("                    error: function (jqXHR, status) {\n");
      out.write("                        console.log(status);\n");
      out.write("                        alert('failed, please check console for errors');\n");
      out.write("                    }\n");
      out.write("                 });\n");
      out.write("           }\n");
      out.write("     });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("header {\n");
      out.write("    background-color:black;\n");
      out.write("    color:white;\n");
      out.write("    text-align:center;\n");
      out.write("    padding:5px;     \n");
      out.write("}\n");
      out.write("nav {\n");
      out.write("    line-height:30px;\n");
      out.write("    height:600px;\n");
      out.write("    width:100px;\n");
      out.write("    float:left;\n");
      out.write("    padding:15px;         \n");
      out.write("}\n");
      out.write("div {\n");
      out.write("    width:450px;\n");
      out.write("    float:left;\n");
      out.write("    padding:10px;        \n");
      out.write("}\n");
      out.write("footer {\n");
      out.write("    color:white;\n");
      out.write("    clear:both;\n");
      out.write("    text-align:center;\n");
      out.write("    padding:5px;         \n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("<h1>Shortener URL Project</h1>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<nav>\n");
      out.write("<button id=\"home\" type=\"button\" style=\"width: 90px\">home</button><br>\n");
      out.write("<br>\n");
      out.write("<button id=\"create\" type=\"button\" style=\"width: 90px\">Shorten URL</button><br>\n");
      out.write("<br>\n");
      out.write("<button type=\"button\" id=\"delete\" style=\"width: 90px\">Delete  URL</button><br>\n");
      out.write("<br>\n");
      out.write("<button type=\"button\" id=\"update\" style=\"width: 90px\">Update  URL</button><br>\n");
      out.write("<br>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"homePage\">\n");
      out.write("<h1 id=\"titel\">\"\"</h1>\n");
      out.write("<p id=\"demo\">This project for software as server (SaaS) course. I used JAVA on the server based on restful.\n");
      out.write("<br>\n");
      out.write("In this project can create short URL, delete it and updete it by regnerate short URL for the same orjginal URL.\n");
      out.write("<br>\n");
      out.write("The database is Mongodb on cloud server in mlab.com .\n");
      out.write("<br>You can get the source code on git hub on this link.\n");
      out.write("<br>https://github.com/malharbi/shortenerURL \n");
      out.write("</p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"createPage\">\n");
      out.write("<h1 style=\"text-align:center;\">Create a Shorten URL</h1>\n");
      out.write("<form method=\"POST\">\n");
      out.write("Post your long URL here\n");
      out.write("<input type=\"text\" name=\"givenURL\" size=\"40\"><br/>\n");
      out.write("<input type=\"submit\" values=\"Shorten URL\">\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"deletePage\">\n");
      out.write("<h1 style=\"text-align:center;\">Delete a URL</h1>\n");
      out.write("<form id=\"delete_form\" method=\"POST\">\n");
      out.write("Enter you Shorten URL to be deleted\n");
      out.write("<input type=\"text\" class=\"ids\" size=\"40\"><br/>\n");
      out.write("<input type=\"submit\">\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"updatePage\">\n");
      out.write("<h1 style=\"text-align:center;\">Update your shorten URL</h1>\n");
      out.write("<form id=\"update_form\" method=\"POST\" >\n");
      out.write("Enter you shorten URL to be update\n");
      out.write("<input type=\"text\" class=\"id\" size=\"40\"><br/>\n");
      out.write("<input type=\"submit\">\n");
      out.write("</form>\n");
      out.write("<div id=\"results\"></div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("Copyright © motaz2.herokuapp.com\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
